### ISSUE TITLE
Issue with installation of glpk 0.4.5

### ISSUE THREAD

**Issue by ghost** [bradfordboyle/pyglpk#31]
Hello Bradford!

I have already installed glpk standalone version on my machine but I can't complete the pyglpk installation. Please see below the issue when trying to "pip install glpk".

(base) C:\Users\simonsa>pip install glpk==0.4.5
Collecting glpk==0.4.5
  Using cached https://files.pythonhosted.org/packages/74/e0/8676d8d5404a8f9aee298985d21aae67b776476b01583ff1a3e0030e2f51/glpk-0.4.5.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: glpk
  Building wheel for glpk (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\simonsa\AppData\Local\Continuum\anaconda3\python.exe' 'C:\Users\simonsa\AppData\Local\Continuum\anaconda3\lib\site-packages\pip\_vendor\pep517\_in_process.py' build_wheel 'C:\Users\simonsa\AppData\Local\Temp\tmpbxzd_xo8'
       cwd: C:\Users\simonsa\AppData\Local\Temp\pip-install-unmgv628\glpk
  Complete output (15 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'glpk' extension
  creating build
  creating build\temp.win-amd64-3.7
  creating build\temp.win-amd64-3.7\Release
  creating build\temp.win-amd64-3.7\Release\src
  C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.26.28801\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DVERSION_NUMBER="0.4.5" -IC:\Users\simonsa\AppData\Local\Continuum\anaconda3\include -IC:\Users\simonsa\AppData\Local\Continuum\anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.26.28801\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" -IC:\glpk-4.65\src /Tcsrc\glpk.c /Fobuild\temp.win-amd64-3.7\Release\src\glpk.obj
  glpk.c
  src\glpk.c(64): error C2440: 'function': cannot convert from 'double' to 'const char *'
  src\glpk.c(64): warning C4024: 'PyModule_AddStringConstant': different types for formal and actual parameter 3
  src\glpk.c(64): error C2143: syntax error: missing ')' before 'constant'
  src\glpk.c(64): error C2059: syntax error: ')'
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.26.28801\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for glpk
  Running setup.py clean for glpk
Failed to build glpk
ERROR: Could not build wheels for glpk which use PEP 517 and cannot be installed directly

It seems there is some contradiction in c code. 

Are you able to help me?

thank you very much
Simone

**Comment by bradfordboyle** [comment]
Thanks for reporting this. I _think_ what's happening is that `VERSION_NUMBER` (which is set to `0.4.5`) is being interpreted as a double instead of a string. I don't have access to a Windows development environment at the moment, but I'll take a look at adding some Windows CI to see if I can reproduce the issue.

**Comment by bradfordboyle** [comment]
Quick status update: I've managed to get an action workflow setup for building and testing on Windows and I've raised a draft PR (#32) to test some quick fixes for building on Windows.

The extension successfully builds and installs but there are some test failures. I haven't looked at the failures to see if these are real failures or just environmental issues.

@SimoneSassi If you can try building from the branch in the PR and let me know if that is working, it would be helpful.

**Comment by ghost** [comment]
Hello,

thanks for working on it.

I have taken the updated version of pyglpk in your repository. Running it with "python setup.py install" I get this error:

\-----------------------------------------------------------------------------------------------\
(base) C:\Users\simonsa\Downloads\extraction\glpk-0.4.6>python setup.py install
Traceback (most recent call last):
  File "setup.py", line 45, in <module>
    defs.append(('VERSION_NUMBER', '"\\"{}\\""'.format(get_version())))
  File "C:\Users\simonsa\AppData\Local\Continuum\anaconda3\lib\site-packages\setuptools_scm\__init__.py", line 144, in get_version
    return _get_version(config)
  File "C:\Users\simonsa\AppData\Local\Continuum\anaconda3\lib\site-packages\setuptools_scm\__init__.py", line 148, in _get_version
    parsed_version = _do_parse(config)
  File "C:\Users\simonsa\AppData\Local\Continuum\anaconda3\lib\site-packages\setuptools_scm\__init__.py", line 118, in _do_parse
    "use git+https://github.com/user/proj.git#egg=proj" % config.absolute_root
LookupError: setuptools-scm was unable to detect version for 'C:\\Users\\simonsa\\Downloads\\extraction\\glpk-0.4.6'.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj

\-----------------------------------------------------------------------------------------------\

**Comment by bradfordboyle** [comment]
I've updated the Windows CI to store a built distribution of the glpk module.  See if you can download this and install it: https://github.com/bradfordboyle/pyglpk/actions/runs/139253390

**Comment by ghost** [comment]
Thanks, but I am not sure how can I install it.

**Comment by bradfordboyle** [comment]
I've just published pyglpk 0.4.6 which should build/install on Windows. You can install it with `pip install glpk==0.4.6`.

**Comment by ghost** [comment]
Hi Bradford,

thanks. unfortunately I still have issues. Please find attached the log when trying to pip install glpk==0.4.6.

[log.txt](https://github.com/bradfordboyle/pyglpk/files/4841918/log.txt)

Simone

**Comment by bradfordboyle** [comment]
It looks like WinGLPK names the library `glpk_4_65.lib` instead of `glpk.lib`. If you rename or copy this file to `glpk.lib` it should compile.
